// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-template/service/account/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/account/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/account/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/account/roles",
				Handler: AddRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/account/roles",
				Handler: GetRoleListHandler(serverCtx),
			},
		},
	)
}
