// Code generated by goctl. DO NOT EDIT.
package types

type RegisterParam struct {
	Name     string `json:"name"`     // 用户名
	Password string `json:"password"` // 密码
}

type LoginParam struct {
	Account  string `json:"account"`  // 账户（手机号/用户名）
	Password string `json:"password"` // 密码
}

type AddRoleParam struct {
	RoleName string `json:"roleName"` // 角色名称
}
