// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-template/service/function/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/function/chromedp",
				Handler: ChromedpHandler(serverCtx),
			},
		},
	)
}
