// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-template/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/list",
				Handler: UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/report/add",
				Handler: AddReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/report/list",
				Handler: GetReportListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/report/delete",
				Handler: DeleteReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/report/edit",
				Handler: EditReportHandler(serverCtx),
			},
		},
	)
}
