// Code generated by goctl. DO NOT EDIT.
package types

type RegisterParam struct {
	UserName string `json:"userName"` // 用户名
	Phone    string `json:"phone"`    // 手机号
	Password string `json:"password"` // 密码
}

type LoginParam struct {
	Account  string `json:"account"`  // 账户（手机号/用户名）
	Password string `json:"password"` // 密码
}

type AddReportParam struct {
	Name      string `json:"name"`      // 报告名称
	Customer  string `json:"customer"`  // 客户名称
	StartTime string `json:"startTime"` // 投放开始时间
	EndTime   string `json:"endTime"`   // 投放结束时间
}

type GetReportListParam struct {
	Filters  ReportFilters `json:"filter,optional"` // 筛选条件
	Page     int64         `json:"page,optional"`
	PageSize int64         `json:"pageSize,optional"`
}

type ReportFilters struct {
	Name     string `json:"name"`     // 报告名称
	Creator  string `json:"creator"`  // 创建者
	Customer string `json:"customer"` // 客户名称
	Time     string `json:"time"`     // 投放时间
}

type DeleteReportParam struct {
	ID int64 `json:"id"` // 报告id
}

type EditReportParam struct {
	ID        int64  `json:"id"`        // 报告id
	Name      string `json:"name"`      // 报告名称
	StartTime string `json:"startTime"` // 投放开始时间
	EndTime   string `json:"endTime"`   // 投放结束时间
}
